### ISSUE TITLE
Confirm component

### ISSUE THREAD

**Issue by ste7een** [EnabApp/Ui#7]
We need a **confirm modal** that content : 

- [ ] text with parameter like ( are you sure to buy {{ param that will send as props with component }} ? ) .
- [ ] confirm and cancel buttons 
- [ ] Resizable

**Comment by Gruce** [comment]
Please put it in `Ui Project`.

Thank you

**Comment by ste7een** [comment]
Hi @Gruce 
I don't have an permission to put it or change it , if you can to give me any permission to change .
Thank you .

**Comment by Gruce** [comment]
Hi @ste7een,

Permissions have been given. check them out.

Thank you

**Comment by ste7een** [comment]
Hello again @Gruce  thank you very much 🥰.
