### ISSUE TITLE
Bottom bar exit icon

### ISSUE THREAD

**Issue by ste7een** [EnabApp/Ui#8]
We need a ( X ) icon on hover on a app sections to exit from an app . 

![Image](https://user-images.githubusercontent.com/64214350/186648137-2ab2cbf9-d6dc-45b7-8b83-cef9ad4214c3.png)

**Comment by Gruce** [comment]
Please put it in Ui Project. But it has been done.

Thank you.

**Comment by ste7een** [comment]
Hello @Gruce 
I tried to change any think on UI project but i don't have a permission and i told @i1Zeus to change it .
Thank you

**Comment by Gruce** [comment]
Hello @ste7een,
I will give you all permissions. @a7med3bd is the responsible for UI not @i1Zeus .

Greetings

**Comment by ste7een** [comment]
Thank you very much 🥰🥰 .
